---
- hosts: 172.31.13.137
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: install webserver
    apt:
      name: apache2 
      state: present

  - name: copy static files into ansible nodes side
    templete:
         src:
         dest: /var/www/html/index.html