---
- hosts: all
  become: yes 
  tasks: 
  - name: install java on ubuntu
    apt:
      name: "{{myjavapackonubuntu}}"
      state: present
    when: ansible_os_family =="debian"

  - name: install java on redhat
    apt:
      name: "{{myjavapackonredhat}}"
      state: present
    when: ansible_os_family =="redhat"