---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="debian"
  
  - name: start apache2
    sevice: 
        name: apache2
        state: restarted
    when: ansible_os_family =="debian"

