---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install apache2
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family =="debian"
  
  - name: start apache2
    service: 
        name: "{{mywebpackonubuntu}}"
        state: restarted
    when: ansible_os_family =="debian"

  - name: install webserver on redhat nodes
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family =="redhat"

  - name: start webserver 
    service:
       name: "{{mywebpackonredhat}}"
       state: started
    when: ansible_os_family =="redhat"
