---
- hosts: mywebservers
  tasks: 
  - name: install apache2 
    apt:
      name: apache2
      state: present

  - name: start apache2
    service:
        name: apache2
        state: restarted

  - name: install git
    apt: 
      name: git 
      state: present

  